### ISSUE TITLE
where did i get it wrong?

### ISSUE THREAD

**Issue by emans841** [fbctf/cromos#3]
python cromos.py --extension ahmpjcflkgiildlgicmcieglgoilbfdp --build bat --token ZJdSSjU9EFAAAAAAAAAACnpp-vC1ejBUTmLkkyClxJ-A2jOFHrlBB2oyWK

         (         )      *         )    (     
   (     )\ )   ( /(    (  `     ( /(    )\ )  
   )\   (()/(   )\())   )\))(    )\())  (()/(  
 (((_)   /(_)) ((_)\   ((_)()\  ((_)\    /(_)) 
 )\___  (_))     ((_)  (_()((_)   ((_)  (_))   
((/ __| | _ \   / _ \  |  \/  |  / _ \  / __|  
 | (__  |   /  | (_) | | |\/| | | (_) | \__ \  
  \___| |_|_\   \___/  |_|  |_|  \___/  |___/
	 
      Version: 1.0 Builds: 1 Modules: 2
       
[!] The extension has already been downloaded
[!] First upload the files to get shared links
[+] Upload files in dropbox
Traceback (most recent call last):
  File "cromos.py", line 75, in <module>
    main()
  File "cromos.py", line 71, in main
    Drive(extension, builds, token).upload()
  File "/root/Desktop/cromos/libs/drive.py", line 71, in upload
    raise e
ValueError: Timeout value connect was Timeout(connect=30, read=30, total=None), but it must be an int, float or None.

**Comment by fbctf** [comment]
Check your internet and try again, it's just a timeout error. Sorry change YOUR private token!
